/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.repository.jdbc.test;

import org.testng.annotations.Test;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.simple.ParameterizedBeanPropertyRowMapper;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.orm.ObjectRetrievalFailureException;
import org.springframework.samples.petclinic.model.Owner;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.samples.petclinic.model.PetType;
import org.springframework.samples.petclinic.model.Visit;
import org.springframework.samples.petclinic.repository.OwnerRepository;
import org.springframework.samples.petclinic.repository.PetRepository;
import org.springframework.samples.petclinic.repository.VisitRepository;
import org.springframework.samples.petclinic.util.EntityUtils;
import org.springframework.stereotype.Repository;
import org.springframework.samples.petclinic.repository.jdbc.*;

public class JdbcPetRepositoryImplTest {

    @Test()
    public List<PetType> findPetTypesTest() throws DataAccessException {
    }

    @Test()
    public Pet findByIdTest() throws DataAccessException {
    }

    @Test()
    public void saveTest() throws DataAccessException {
    }

    /**
     * Creates a {@link MapSqlParameterSource} based on data values from the supplied {@link Pet} instance.
     */
    @Test()
    private MapSqlParameterSource createPetParameterSourceTest() {
    }
}
