/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.repository.jdbc.test;

import org.testng.annotations.Test;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.samples.petclinic.repository.jdbc.*;

public class JdbcPetTest {

    @Test()
    public void setTypeIdTest() {
    }

    @Test()
    public int getTypeIdTest() {
    }

    @Test()
    public void setOwnerIdTest() {
    }

    @Test()
    public int getOwnerIdTest() {
    }
}
