/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.repository.jdbc.test;

import org.testng.annotations.Test;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import org.joda.time.DateTime;
import org.springframework.jdbc.core.simple.ParameterizedRowMapper;
import org.springframework.samples.petclinic.repository.jdbc.*;

public class JdbcPetRowMapperTest {

    @Test()
    public JdbcPet mapRowTest() throws SQLException {
    }
}
