/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.repository.jpa.test;

import org.testng.annotations.Test;
import java.util.Collection;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import org.springframework.orm.hibernate3.support.OpenSessionInViewFilter;
import org.springframework.samples.petclinic.model.Owner;
import org.springframework.samples.petclinic.repository.OwnerRepository;
import org.springframework.stereotype.Repository;
import org.springframework.samples.petclinic.repository.jpa.*;

public class JpaOwnerRepositoryImplTest {

    /**
     * Important: in the current version of this method, we load Owners with all their Pets and Visits while 
     * we do not need Visits at all and we only need one property from the Pet objects (the 'name' property).
     * There are some ways to improve it such as:
     * - creating a Ligtweight class (example here: https://community.jboss.org/wiki/LightweightClass)
     * - Turning on lazy-loading and using {@link OpenSessionInViewFilter}
     */
    @Test()
    public Collection<Owner> findByLastNameTest() {
    }

    @Test()
    public Owner findByIdTest() {
    }

    @Test()
    public void saveTest() {
    }
}
