/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.repository.jpa.test;

import org.testng.annotations.Test;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.samples.petclinic.model.PetType;
import org.springframework.samples.petclinic.repository.PetRepository;
import org.springframework.stereotype.Repository;
import org.springframework.samples.petclinic.repository.jpa.*;

public class JpaPetRepositoryImplTest {

    @Test()
    public List<PetType> findPetTypesTest() {
    }

    @Test()
    public Pet findByIdTest() {
    }

    @Test()
    public void saveTest() {
    }
}
