/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.repository.jpa.test;

import org.testng.annotations.Test;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import org.springframework.samples.petclinic.model.Visit;
import org.springframework.samples.petclinic.repository.VisitRepository;
import org.springframework.stereotype.Repository;
import org.springframework.samples.petclinic.repository.jpa.*;

public class JpaVisitRepositoryImplTest {

    @Test()
    public void saveTest() {
    }

    @Test()
    public List<Visit> findByPetIdTest() {
    }
}
