/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.repository.jpa.test;

import org.testng.annotations.Test;
import java.util.Collection;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.samples.petclinic.model.Vet;
import org.springframework.samples.petclinic.repository.VetRepository;
import org.springframework.stereotype.Repository;
import org.springframework.samples.petclinic.repository.jpa.*;

public class JpaVetRepositoryImplTest {

    @Test()
    public Collection<Vet> findAllTest() {
    }
}
