/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.web.test;

import org.testng.annotations.Test;
import java.util.Collection;
import java.util.Map;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.samples.petclinic.model.Owner;
import org.springframework.samples.petclinic.service.ClinicService;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;
import org.springframework.web.bind.support.SessionStatus;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.samples.petclinic.web.*;

public class OwnerControllerTest {

    @Test()
    public void setAllowedFieldsTest() {
    }

    @Test()
    public String initCreationFormTest() {
    }

    @Test()
    public String processCreationFormTest() {
    }

    @Test()
    public String initFindFormTest() {
    }

    @Test()
    public String processFindFormTest() {
    }

    @Test()
    public String initUpdateOwnerFormTest() {
    }

    @Test()
    public String processUpdateOwnerFormTest() {
    }

    /**
     * Custom handler for displaying an owner.
     *
     * @param ownerId the ID of the owner to display
     * @return a ModelMap with the model attributes for the view
     */
    @Test()
    public ModelAndView showOwnerTest() {
    }
}
