/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.web.test;

import org.testng.annotations.Test;
import java.text.ParseException;
import java.util.Collection;
import java.util.Locale;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.Formatter;
import org.springframework.samples.petclinic.model.PetType;
import org.springframework.samples.petclinic.service.ClinicService;
import org.springframework.samples.petclinic.web.*;

public class PetTypeFormatterTest {

    @Test()
    public String printTest() {
    }

    @Test()
    public PetType parseTest() throws ParseException {
    }
}
