/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.web.test;

import org.testng.annotations.Test;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.util.StringUtils;
import org.springframework.validation.Errors;
import org.springframework.samples.petclinic.web.*;

public class PetValidatorTest {

    @Test()
    public void validateTest() {
    }
}
