/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.web.test;

import org.testng.annotations.Test;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.samples.petclinic.model.Vets;
import org.springframework.samples.petclinic.service.ClinicService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.samples.petclinic.web.*;

public class VetControllerTest {

    @Test()
    public String showVetListTest() {
    }
}
