/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.web.test;

import org.testng.annotations.Test;
import java.util.Map;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.samples.petclinic.model.Visit;
import org.springframework.samples.petclinic.service.ClinicService;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;
import org.springframework.web.bind.support.SessionStatus;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.samples.petclinic.web.*;

public class VisitControllerTest {

    @Test()
    public void setAllowedFieldsTest() {
    }

    @Test()
    public String initNewVisitFormTest() {
    }

    @Test()
    public String processNewVisitFormTest() {
    }

    @Test()
    public ModelAndView showVisitsTest() {
    }
}
