/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.util.test;

import org.testng.annotations.Test;
import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.springframework.jmx.export.annotation.ManagedAttribute;
import org.springframework.jmx.export.annotation.ManagedOperation;
import org.springframework.jmx.export.annotation.ManagedResource;
import org.springframework.util.StopWatch;
import org.springframework.samples.petclinic.util.*;

public class CallMonitoringAspectTest {

    @Test()
    public void setEnabledTest() {
    }

    @Test()
    public boolean isEnabledTest() {
    }

    @Test()
    public void resetTest() {
    }

    @Test()
    public int getCallCountTest() {
    }

    @Test()
    public long getCallTimeTest() {
    }

    @Test()
    public Object invokeTest() throws Throwable {
    }
}
