/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.util.test;

import org.testng.annotations.Test;
import java.util.Collection;
import org.springframework.orm.ObjectRetrievalFailureException;
import org.springframework.samples.petclinic.model.BaseEntity;
import org.springframework.samples.petclinic.util.*;

public class EntityUtilsTest {

    /**
     * Look up the entity of the given class with the given id in the given collection.
     *
     * @param entities    the collection to search
     * @param entityClass the entity class to look up
     * @param entityId    the entity id to look up
     * @return the found entity
     * @throws ObjectRetrievalFailureException
     *          if the entity was not found
     */
    @Test()
    public static <T extends BaseEntity> T getByIdTest() throws ObjectRetrievalFailureException {
    }
}
