/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.model.test;

import org.testng.annotations.Test;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import org.springframework.samples.petclinic.model.*;

public class BaseEntityTest {

    @Test()
    public void setIdTest() {
    }

    @Test()
    public Integer getIdTest() {
    }

    @Test()
    public boolean isNewTest() {
    }
}
