/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.model.test;

import org.testng.annotations.Test;
import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import org.springframework.samples.petclinic.model.*;

public class NamedEntityTest {

    @Test()
    public void setNameTest() {
    }

    @Test()
    public String getNameTest() {
    }

    @Test()
    public String toStringTest() {
    }
}
