/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.model.test;

import org.testng.annotations.Test;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Digits;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;
import org.springframework.core.style.ToStringCreator;
import org.springframework.samples.petclinic.model.*;

public class OwnerTest {

    @Test()
    public String getAddressTest() {
    }

    @Test()
    public void setAddressTest() {
    }

    @Test()
    public String getCityTest() {
    }

    @Test()
    public void setCityTest() {
    }

    @Test()
    public String getTelephoneTest() {
    }

    @Test()
    public void setTelephoneTest() {
    }

    @Test()
    protected void setPetsInternalTest() {
    }

    @Test()
    protected Set<Pet> getPetsInternalTest() {
    }

    @Test()
    public List<Pet> getPetsTest() {
    }

    @Test()
    public void addPetTest() {
    }

    /**
     * Return the Pet with the given name, or null if none found for this Owner.
     *
     * @param name to test
     * @return true if pet name is already in use
     */
    @Test()
    public Pet getPetTest() {
    }

    /**
     * Return the Pet with the given name, or null if none found for this Owner.
     *
     * @param name to test
     * @return true if pet name is already in use
     */
    @Test()
    public Pet getPetTest() {
    }

    @Test()
    public String toStringTest() {
    }
}
