/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.model.test;

import org.testng.annotations.Test;
import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.samples.petclinic.model.*;

public class PersonTest {

    @Test()
    public String getFirstNameTest() {
    }

    @Test()
    public void setFirstNameTest() {
    }

    @Test()
    public String getLastNameTest() {
    }

    @Test()
    public void setLastNameTest() {
    }
}
