/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.model.test;

import org.testng.annotations.Test;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;
import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.samples.petclinic.model.*;

public class PetTest {

    @Test()
    public void setBirthDateTest() {
    }

    @Test()
    public DateTime getBirthDateTest() {
    }

    @Test()
    public void setTypeTest() {
    }

    @Test()
    public PetType getTypeTest() {
    }

    @Test()
    protected void setOwnerTest() {
    }

    @Test()
    public Owner getOwnerTest() {
    }

    @Test()
    protected void setVisitsInternalTest() {
    }

    @Test()
    protected Set<Visit> getVisitsInternalTest() {
    }

    @Test()
    public List<Visit> getVisitsTest() {
    }

    @Test()
    public void addVisitTest() {
    }
}
