/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.model.test;

import org.testng.annotations.Test;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.springframework.samples.petclinic.model.*;

public class PetTypeTest {
}
