/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.model.test;

import org.testng.annotations.Test;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import org.springframework.samples.petclinic.model.*;

public class VetsTest {

    @Test()
    public List<Vet> getVetListTest() {
    }
}
