/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.model.test;

import org.testng.annotations.Test;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;
import org.springframework.samples.petclinic.model.*;

public class VetTest {

    @Test()
    protected void setSpecialtiesInternalTest() {
    }

    @Test()
    protected Set<Specialty> getSpecialtiesInternalTest() {
    }

    @Test()
    public List<Specialty> getSpecialtiesTest() {
    }

    @Test()
    public int getNrOfSpecialtiesTest() {
    }

    @Test()
    public void addSpecialtyTest() {
    }
}
