/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.model.test;

import org.testng.annotations.Test;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.NotEmpty;
import org.joda.time.DateTime;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.samples.petclinic.model.*;

public class VisitTest {

    /**
     * Getter for property date.
     *
     * @return Value of property date.
     */
    @Test()
    public DateTime getDateTest() {
    }

    /**
     * Setter for property date.
     *
     * @param date New value of property date.
     */
    @Test()
    public void setDateTest() {
    }

    /**
     * Getter for property description.
     *
     * @return Value of property description.
     */
    @Test()
    public String getDescriptionTest() {
    }

    /**
     * Setter for property description.
     *
     * @param description New value of property description.
     */
    @Test()
    public void setDescriptionTest() {
    }

    /**
     * Getter for property pet.
     *
     * @return Value of property pet.
     */
    @Test()
    public Pet getPetTest() {
    }

    /**
     * Setter for property pet.
     *
     * @param pet New value of property pet.
     */
    @Test()
    public void setPetTest() {
    }
}
