/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.repository.springdatajpa.test;

import org.testng.annotations.Test;
import java.util.Collection;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.Repository;
import org.springframework.data.repository.query.Param;
import org.springframework.samples.petclinic.model.Owner;
import org.springframework.samples.petclinic.repository.OwnerRepository;
import org.springframework.samples.petclinic.repository.springdatajpa.*;

public class SpringDataOwnerRepositoryTest {

    @Test()
    public Collection<Owner> findByLastNameTest() {
    }

    @Test()
    public Owner findByIdTest() {
    }
}
