/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.repository.springdatajpa.test;

import org.testng.annotations.Test;
import java.util.List;
import org.springframework.dao.DataAccessException;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.Repository;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.samples.petclinic.model.PetType;
import org.springframework.samples.petclinic.repository.PetRepository;
import org.springframework.samples.petclinic.repository.springdatajpa.*;

public class SpringDataPetRepositoryTest {

    @Test()
    List<PetType> findPetTypesTest() throws DataAccessException {
    }
}
