package cn.shenyanchao.ut.common;

/**
 * Date:  6/18/13
 * Time:  1:45 PM
 *
 * @author shenyanchao
 */
public interface FileComments {

    public static final String GENERATOR_COMMENT = "This TestClass is Auto Generated By ut-maven-plugin";
}
