package cn.shenyanchao.ut.common;

/**
 * @author shenyanchao
 *         Date:  6/18/13
 *         Time:  1:45 PM
 */
public interface FileComments {

    public static final String GENERATOR_COMMENT = "This TestClass is Auto Generated By ut-maven-plugin";
}
