/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.repository.test;

import org.testng.annotations.Test;
import java.util.List;
import org.springframework.dao.DataAccessException;
import org.springframework.samples.petclinic.model.BaseEntity;
import org.springframework.samples.petclinic.model.Visit;
import org.springframework.samples.petclinic.repository.*;

public class VisitRepositoryTest {

    /**
     * Save a <code>Visit</code> to the data store, either inserting or updating it.
     *
     * @param visit the <code>Visit</code> to save
     * @see BaseEntity#isNew
     */
    @Test()
    void saveTest() throws DataAccessException {
    }

    @Test()
    List<Visit> findByPetIdTest() {
    }
}
