/**This TestClass is Auto Generated By ut-maven-plugin*/
package test;

import org.testng.annotations.Test;

public class DefaultPackageTypeTest {

    @Test(description = "申艳超的测试用例")
    public void justsTest() {
        System.out.println("I already modify the test,and ut-maven-plugin should not override");
    }
}
