/**This TestClass is Auto Generated By ut-maven-plugin*/
package org.springframework.samples.petclinic.service.test;

import org.testng.annotations.Test;
import java.util.Collection;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.dao.DataAccessException;
import org.springframework.samples.petclinic.model.Owner;
import org.springframework.samples.petclinic.model.Pet;
import org.springframework.samples.petclinic.model.PetType;
import org.springframework.samples.petclinic.model.Vet;
import org.springframework.samples.petclinic.model.Visit;
import org.springframework.samples.petclinic.repository.OwnerRepository;
import org.springframework.samples.petclinic.repository.PetRepository;
import org.springframework.samples.petclinic.repository.VetRepository;
import org.springframework.samples.petclinic.repository.VisitRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.samples.petclinic.service.*;

public class ClinicServiceImplTest {

    @Test()
    public Collection<PetType> findPetTypesTest() throws DataAccessException {
    }

    @Test()
    public Owner findOwnerByIdTest() throws DataAccessException {
    }

    @Test()
    public Collection<Owner> findOwnerByLastNameTest() throws DataAccessException {
    }

    @Test()
    public void saveOwnerTest() throws DataAccessException {
    }

    @Test()
    public void saveVisitTest() throws DataAccessException {
    }

    @Test()
    public Pet findPetByIdTest() throws DataAccessException {
    }

    @Test()
    public void savePetTest() throws DataAccessException {
    }

    @Test()
    public Collection<Vet> findVetsTest() throws DataAccessException {
    }
}
